### ISSUE TITLE
Statistics are giving no results

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/dmr#305]
### Descriptive summary

When going into the statistics reporting feature for DMR and after selecting date ranges, the report returns zero or nothing.
### Rationale

Fix is needed for staff reporting purposes.

------
![dmr](https://user-images.githubusercontent.com/4314914/45842870-cb9cb900-bcd2-11e8-82ab-3bbf05ca2092.png)

**Comment by VivianChu** [comment]
@gamontoya - I tried different date ranges for audio and results are returned.  I tried video within that range July 2 - Sept 19, and results are also returned.  Attached are the screen shot.  I tried to search for summer in courses search and don't see any audio courses created.  Could you try again?  Thanks

![videostatfromjuly](https://user-images.githubusercontent.com/1864660/45850245-3efdf500-bcea-11e8-99f2-dd899910f88d.png)
![audiostatfrommay](https://user-images.githubusercontent.com/1864660/45850246-3efdf500-bcea-11e8-9388-144ebdc3bfc2.png)

**Comment by gamontoya** [comment]
@VivianChu I'm having Kirk try to replicate.

**Comment by VivianChu** [comment]
@gamontoya - For audio stats page, items added and # courses created still works fine.  However, the records created and views don't work.  The records created stats doesn't work because the log from prod is different than staging.  Prod log doesn't have referer field.  I updated the query not to use that field and it works fine in staging now.  The # of views doesn't work because I use the field x_spos field from the wowza access log as recommended by wowza support.  It works fine before with Wowza Streaming Engine 4.6.0.01.  It doesn't work with the current upgraded Wowza Streaming Engine version 4.7.6 (build 20180731190812).  That field x_spos always returns 0.  Ron just submitted a request to wowza asking why it is always 0.  While waiting for the respond, I use different approach by calculating the play time and stop time.  The code is deployed to staging now.  Here's the screen shot.  Could you review it?  Thanks 
![audiostats](https://user-images.githubusercontent.com/1864660/45983853-52bf9900-c013-11e8-9926-94a11da4dc5b.png)

**Comment by gamontoya** [comment]
@VivianChu Looks good.

**Comment by gamontoya** [comment]
@VivianChu Approved for a release on Monday. I'll get the ticket open.
