### ISSUE TITLE
Exact string searches (with quotes) not working 

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/dmr#87]
1. A search for "Toy Story" in quotes results in 0 hits.
2. Search _Toy Story_ without quotes and you get three screens of results. Note that Toy Story and Toy Story 2 appear on the second page.
3. For #2, the results are in alpha order. Should it not be based on relevancy?

![2](https://cloud.githubusercontent.com/assets/4314914/19742838/a8ed6b36-9b7b-11e6-9866-24c825451583.png)

**Comment by mcritchlow** [comment]
Is this a bug, or just a feature that was never built? I'm curious if this makes sense to do now vs as part of the STAR/DMR merger. /cc @VivianChu

**Comment by VivianChu** [comment]
@mcritchlow The exact search string works before without using the quotes.  However, since this change for search https://lib-jira.ucsd.edu:8443/browse/DMR-88 , it's not working anymore.  I don't recall that we're required to use the quotes for exact search string before.  The search never built to support the quotes search.  I think using the quotes to differentiate the exact search string is a good idea since the search can't tell when people want to do combine search or do exact search.  What do you think?  I don't know if we can call this feature a bug or not.

**Comment by mcritchlow** [comment]
Thanks @VivianChu. I'm not sure how to classify this then. We'll need some guidance from @gamontoya

**Comment by gamontoya** [comment]
@VivianChu @mcritchlow Well if it wasn't ever coded to work that way, then it has to be a feature.

**Comment by mcritchlow** [comment]
@gamontoya sorry, i should have been more clear in my response to @VivianChu .

Since it's not a bug, should this feature file in with the STAR/DMR project or be treated independently?

**Comment by gamontoya** [comment]
@mcritchlow The issue was really tied to DMR (not STAR/DMR integration), so it should be treated independently.
